services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: monitoreo_rv2
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3339:3306"

  web:
    build: .
    command: sh -c "sleep 10 && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "127:8000"
    depends_on:
      - db

  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    command: node /app/static/js/server.js
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
      - web

volumes:
  mysql_data: