# Generated by Django 5.0.6 on 2024-10-15 19:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisenarEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_evaluacion', models.CharField(max_length=100)),
                ('casos_estres', models.CharField(choices=[('caso1', 'Caso 1'), ('caso2', 'Caso 2')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ECGData2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bpm', models.IntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Expositores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(max_length=10)),
                ('semestre_academico', models.IntegerField()),
                ('carrera', models.CharField(max_length=100)),
                ('observacion_inicial', models.TextField()),
                ('observacion_final', models.TextField(blank=True, default='sin información', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FrecuenciaCardiaca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia', models.FloatField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Practicante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=255)),
                ('apellidoP_usuario', models.CharField(max_length=255)),
                ('apellidoM_usuario', models.CharField(max_length=255)),
                ('fecha_ingreso', models.DateField()),
                ('observacionInicial', models.CharField(max_length=255)),
                ('observacionFinal', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('function_name', models.CharField(max_length=100)),
                ('tag_name', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionRealizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_evaluador', models.CharField(max_length=100)),
                ('fecha_evaluacion', models.DateField()),
                ('observacion_inicial', models.TextField()),
                ('observacion_final', models.TextField(blank=True, null=True)),
                ('tiempo_exposicion', models.CharField(default='00:00:00', max_length=8)),
                ('video_evaluacion', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('evaluacion_aplicada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.evaluacion')),
                ('expositor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.expositores')),
            ],
        ),
        migrations.CreateModel(
            name='ECGData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('value', models.FloatField()),
                ('expositor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ecg_data', to='tasks.expositores')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.evaluacion')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.scenario')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='scenarios',
            field=models.ManyToManyField(related_name='evaluaciones', through='tasks.EvaluacionScenario', to='tasks.scenario'),
        ),
        migrations.CreateModel(
            name='CasoDeEstres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulation_id', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('duration', models.DurationField()),
                ('scene', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('scenarios', models.ManyToManyField(to='tasks.scenario')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dateCompleted', models.DateTimeField(null=True)),
                ('important', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=255)),
                ('apellidoP_usuario', models.CharField(max_length=255)),
                ('apellidoM_usuario', models.CharField(max_length=255)),
                ('email_usuario', models.EmailField(max_length=255)),
                ('password_usuario', models.CharField(max_length=255)),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.rol')),
            ],
        ),
    ]
