# Generated by Django 5.0.6 on 2024-09-11 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionRealizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_evaluador', models.CharField(max_length=100)),
                ('fecha_evaluacion', models.DateField()),
                ('observacion_inicial', models.TextField()),
                ('observacion_final', models.TextField(blank=True, null=True)),
                ('tiempo_exposicion', models.DurationField(blank=True, null=True)),
                ('video_evaluacion', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('evaluacion_aplicada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.evaluacion')),
                ('expositor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.expositores')),
            ],
        ),
    ]
