# Generated by Django 5.0.6 on 2024-10-22 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_ecgdata2_idevaluacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bpm_data', models.JSONField()),
                ('evaluacion_realizada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.evaluacion')),
            ],
        ),
    ]
