# Generated by Django 5.0.6 on 2024-09-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_evaluacionrealizada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionrealizada',
            name='tiempo_exposicion',
            field=models.CharField(default='00:00:00', max_length=8),
        ),
    ]
