# Generated by Django 5.0.6 on 2024-09-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_evaluacionrealizada_tiempo_exposicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expositores',
            name='observacion_final',
            field=models.TextField(blank=True, default='sin información', null=True),
        ),
    ]
