# Generated by Django 5.0.6 on 2024-10-22 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_evaluaciondata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecgdata2',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
