# Generated by Django 5.0.6 on 2024-07-04 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_evaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_exposicion', models.CharField(max_length=20)),
                ('fecha_evaluacion', models.DateField()),
                ('nombre_evaluador', models.CharField(max_length=100)),
                ('observaciones', models.TextField()),
            ],
        ),
    ]
