# Generated by Django 5.0.6 on 2024-07-22 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_evaluacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practicante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=255)),
                ('apellidoP_usuario', models.CharField(max_length=255)),
                ('apellidoM_usuario', models.CharField(max_length=255)),
                ('fecha_ingreso', models.DateField()),
                ('observacionInicial', models.CharField(max_length=255)),
                ('observacionFinal', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=255)),
                ('apellidoP_usuario', models.CharField(max_length=255)),
                ('apellidoM_usuario', models.CharField(max_length=255)),
                ('email_usuario', models.EmailField(max_length=255)),
                ('password_usuario', models.CharField(max_length=255)),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.rol')),
            ],
        ),
    ]
