# Generated by Django 5.0.6 on 2024-07-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_practicante_rol_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisenarEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_evaluacion', models.CharField(max_length=100)),
                ('casos_estres', models.CharField(choices=[('caso1', 'Caso 1'), ('caso2', 'Caso 2')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='casos_estres',
            field=models.CharField(choices=[('caso1', 'Caso 1'), ('caso2', 'Caso 2')], default='caso1', max_length=50),
            preserve_default=False,
        ),
    ]
