# Generated by Django 5.0.6 on 2024-08-06 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_expositor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expositor',
            name='carrera',
        ),
        migrations.RemoveField(
            model_name='expositor',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='expositor',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='expositor',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='expositor',
            name='observacion_final',
        ),
        migrations.RemoveField(
            model_name='expositor',
            name='observacion_inicial',
        ),
        migrations.RemoveField(
            model_name='expositor',
            name='semestre_academico',
        ),
    ]
