# Generated by Django 5.0.6 on 2024-08-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_remove_expositor_carrera_remove_expositor_edad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expositor',
            name='carrera',
            field=models.CharField(default='Sin especificar', max_length=100),
        ),
        migrations.AddField(
            model_name='expositor',
            name='edad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='expositor',
            name='fecha_nacimiento',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AddField(
            model_name='expositor',
            name='genero',
            field=models.CharField(default='No especificado', max_length=10),
        ),
        migrations.AddField(
            model_name='expositor',
            name='observacion_final',
            field=models.TextField(blank=True, default='Sin observación', null=True),
        ),
        migrations.AddField(
            model_name='expositor',
            name='observacion_inicial',
            field=models.TextField(default='Sin observación'),
        ),
        migrations.AddField(
            model_name='expositor',
            name='semestre_academico',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='fecha_ingreso',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='nombre',
            field=models.CharField(default='Sin especificar', max_length=100),
        ),
    ]
