# Generated by Django 5.0.6 on 2024-08-07 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_expositores_delete_expositor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ECGData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('value', models.FloatField()),
            ],
        ),
    ]
