# Generated by Django 5.0.6 on 2024-08-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_alter_ecgdata_expositor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expositores',
            name='observacion_final',
            field=models.TextField(),
        ),
    ]
