# Generated by Django 5.0.6 on 2024-08-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_alter_expositores_observacion_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expositores',
            name='observacion_final',
            field=models.TextField(default='sin información'),
        ),
    ]
