# Generated by Django 5.0.6 on 2024-09-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_alter_expositores_observacion_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='casos_estres',
            field=models.JSONField(default=list),
        ),
    ]
