# Generated by Django 5.0.6 on 2024-09-09 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_alter_expositores_observacion_final'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('function_name', models.CharField(max_length=100)),
                ('tag_name', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CasoDeEstres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulation_id', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('duration', models.DurationField()),
                ('scene', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('expositor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='casos_de_estres', to='tasks.expositores')),
                ('scenarios', models.ManyToManyField(to='tasks.scenario')),
            ],
        ),
    ]
