# Generated by Django 5.0.6 on 2024-09-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_evaluacion_casos_estres'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasoEstres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('duracion', models.IntegerField()),
            ],
        ),
    ]
