# Generated by Django 5.0.6 on 2024-09-09 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_scenario_casodeestres'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='casos_de_estres',
            field=models.ManyToManyField(related_name='evaluaciones', to='tasks.casodeestres'),
        ),
    ]
