# Generated by Django 5.0.6 on 2024-09-09 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_casoestres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacion',
            name='casos_estres',
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='casos_estres',
            field=models.ManyToManyField(blank=True, to='tasks.casoestres'),
        ),
    ]
